### PR TITLE
Update to Angular 13

### PR DESCRIPTION
**Pull request by jordanpowell88**
I am working on a cypress project that requires Angular 12+ (Webpack 5) and wanted to use this repo for the example. Therefore this PR updates this from Angular 11 to 13

### CODE REVIEW

**Comment by trungk18** [comment]
Thanks @jordanpowell88 🍻 However, the CI is still failing. Could you please help to take a look?

image

**Comment by trungk18** [comment]
@jordanpowell88 Thanks, I'll checkout your branch and do a quick check later today. Sorry for the wait 🤣

**Comment by trungk18** [comment]
@jordanpowell88 I am trying to fix the build issue on Netlify. By the way, I also did a major refactoring on the folder structure after merging your PR, hope It didn't come as a surprise

**Comment by jordanpowell88** [comment]
Thanks! I'll rebase and see what happens....YOLO!

**Pull request merged**
